on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: docker compose deploy
        uses: Aldoggutierrez/hello-world-composite-action@94cd0fb2b60fe5341af0c5dcca05c2a7864e4223
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: 'enlacebooking.travel'
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          docker-host: ${{ secrets.DOCKER_HOST }}
          pull-images: "true"