on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Create SSH key
        run: |
            install -m 600 -D /dev/null ~/.ssh/id_rsa
            echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
            ssh-keyscan -H enlacebooking.travel > ~/.ssh/known_hosts
        shell: bash
      - name: checkout repository
        uses: actions/checkout@v4
      - name: deploy docker compose file
        run: docker compose up -d
        shell: bash
        env:
          DOCKER_HOST: ${{secrets.DOCKER_HOST}}
