on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: docker compose deploy
        uses: Aldoggutierrez/docker-compose-deploy-action@v1.1
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-host: 'enlacebooking.travel'
          registry-username: ${{ secrets.REGISTRY_USERNAME }}
          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
          docker-host: ${{ secrets.DOCKER_HOST }}
          pull-images: "true"
          docker-registry: "harbor.enlacebooking.travel"
          compose-project-name: "action"
